### ISSUE TITLE
Get everyone as a collaborator.

### ISSUE THREAD

**Issue by daniel-dsouza** [daniel-dsouza/CSE360#1]
please comment below with your irl name and check your name

- [x] Ryan Ang
- [x] Stephanie Bui
- [x] Daniel D'Souza
- [ ] Cameron Dudley
- [x] Rie Hinze
- [x] James Hutchins
- [x] Haisheng Lin
- [x] Jaime Romero
- [x] Vincent Rose

**Comment by rang1** [comment]
rang1 is Ryan Ang

**Comment by beastlymonkey** [comment]
Jaime Romero

**Comment by vinnybod** [comment]
Vincent Rose

**Comment by haisheng-lin** [comment]
Haisheng Lin

**Comment by jkhutch3** [comment]
James Hutchins

**Comment by stephbui1** [comment]
Stephanie Bui

**Comment by rvhinze** [comment]
Rie Hinze

**Comment by daniel-dsouza** [comment]
i want to close this, I'll assume Cameron knows what to do.
