### ISSUE TITLE
Need a get all prescriptions funtions

### ISSUE THREAD

**Issue by daniel-dsouza** [daniel-dsouza/CSE360#110]
input: none.
return: an arraylist of prescriptions types.

why: reasons.

**Comment by rang1** [comment]
I think i added this. please double check. under DoctortSQL class
i will migrate to PresciptionSQL class once james gets his code running.

**Comment by daniel-dsouza** [comment]
i'll check sunday.

**Comment by daniel-dsouza** [comment]
works.
