### ISSUE TITLE
Mismatched names in Update Lab Report

### ISSUE THREAD

**Issue by vinnybod** [daniel-dsouza/CSE360#126]
![image](https://cloud.githubusercontent.com/assets/9831420/10871642/0f795092-80aa-11e5-8ed9-5ca293287628.png)
I can do this my myself, but figured we should wait til after this deliverable of unit tests. I just think it looks a little funky having the title and the button not match. The title says Report while the button says Test

**Comment by rang1** [comment]
fixed
