### ISSUE TITLE
Validation of PatientInfo fields

### ISSUE THREAD

**Issue by rvabhishek** [daniel-dsouza/CSE360#21]
Email validation
Ph number validation (only numbers I guess)
Fname and Lname validation (no special characters)
Age: only numbers (between 0 and 150)
SSN; only numbers

@Colmbus72 
@jkhutch3

**Comment by daniel-dsouza** [comment]
please reimplement with http://mvnrepository.com/artifact/org.webjars/jquery-maskedinput/1.4.0
