### ISSUE TITLE
Page 34: Appointment: date validation

### ISSUE THREAD

**Issue by rvabhishek** [daniel-dsouza/CSE360#24]
Page 34: Appointment: date validation

@daniel-dsouza 
@Colmbus72 
@vinnybod 
@jkhutch3 
@rvhinze

**Comment by vinnybod** [comment]
It's all through dropdowns so I'm assuming the only validation that needs to be added is making sure all fields are filled in? @rvabhishek

**Comment by daniel-dsouza** [comment]
@vinnybod I'll say yes.

**Comment by daniel-dsouza** [comment]
good 'nough.

**Comment by vinnybod** [comment]
Why would this be closed if we haven't implemented it yet?
