### ISSUE TITLE
restrict the number of characters to 40.

### ISSUE THREAD

**Issue by rvabhishek** [daniel-dsouza/CSE360#25]
Limit the field characters to 40 on on pages.
numbers need to be only 10.

@daniel-dsouza 
@Colmbus72 
@vinnybod 
@jkhutch3 
@rvhinze

**Comment by daniel-dsouza** [comment]
i'm thinking that this will be implemented in global CSS.

**Comment by daniel-dsouza** [comment]
implemented in global jquery.
